/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Button, StyleSheet, View} from 'react-native';
import Zoom from '@fireflyhealth/react-native-zoom';
const zoomUserType = 2; // 2 - pro user
const config = {
  zoom: {
    appKey: 'qdP8eik7WeomCuj5ZeiPlvtSwOfWM3zSHJMz', // TODO: appKey
    appSecret: 'SCBFL9wTln7gNeBZM7Voh59NCL5bTtpYBINY', // TODO appSecret
    domain: 'zoom.us',
  },
};
export default class App extends Component {
  zakTokenRaw = ''; // TODO: meeting zak
  meetingNo = '3990328712'; // TODO: meeting number

  async init() {
    try {
      const initializeResult = await Zoom.initialize(
        config.zoom.appKey,
        config.zoom.appSecret,
        config.zoom.domain,
      );
      console.warn(initializeResult);
    } catch (e) {
      console.warn(e);
    }
  }

  async start() {
    const displayName = 'Test mentor';
    try {
      const startMeetingResult = await Zoom.joinMeeting(
        '3990328712',
        displayName,
      );
      console.log(startMeetingResult);
    } catch (e) {
      console.warn({e});
    }
  }

  render() {
    return (
      <View style={styles.container}>
        <View style={styles.buttonWrapper}>
          <Button title="Init()" onPress={this.init} />
        </View>
        <View style={styles.buttonWrapper}>
          <Button title="Start()" onPress={this.start} />
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonWrapper: {
    margin: 5,
  },
});
